baseURL: 'https://blog.spurgeon.dev/'
languageCode: en-us
title: Developing Ideas
theme: PaperMod
publishDir: docs
params:
  defaultTheme: light
  disableThemeToggle: false 
  ShowCodeCopyButtons: true
  ShowReadingTime: true

